version: '3'

services:
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    volumes:
      - ../Grask-backend/assets:/assets
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - reactjs
      - django
  reactjs:
    build:
      dockerfile: Dockerfile
      context: ../Grask-frontend
    volumes: 
      - /app/node_modules
      - ../Grask-frontend:/app
    stdin_open: true
    expose:
      - "3000"
  django:
    build: 
      dockerfile: Dockerfile
      context: ../Grask-backend
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn Grask_backend.wsgi -b 
      - ../Grask-backend:/app
      - ../Grask-backend/assets:/assets
    expose:
      - "8000"
    env_file:
          - ../Grask-backend/.env.dev