version: '3'

services:
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - reactjs
      - django
  reactjs:
    build:
      dockerfile: Dockerfile
      context: ../Grask-frontend
    stdin_open: true
  django:
    build: 
      dockerfile: Dockerfile
      context: ../Grask-backend
    command: bash -c "python manage.py collectstatic --no-input && gunicorn -w 4 Grask_backend.wsgi -b 0.0.0.0:8000"
    env_file:
          - ../Grask-backend/.env.prod